# owner: wp-publish
"""Build and send per-member filtered email digests from WordPress posts.

Standalone script that runs on its own schedule (separate from the main
pipeline). Queries WordPress for recent articles and member preferences,
then sends each member a filtered digest containing only articles
matching their selected clinical topics.

Usage:
    python -m src.distribute.wp_digest --domain stroke
"""

import argparse
import logging
import os
from datetime import datetime, timedelta, timezone

import httpx
import resend

from src.config import load_wp_config, load_email_config
from src.distribute.email_send import markdown_to_html
from src.distribute.wp_members import Member, fetch_members

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("wp_digest")


def fetch_recent_posts(
    site_url: str,
    taxonomy: str,
    days: int = 7,
) -> list[dict]:
    """Fetch recent WordPress posts with their taxonomy terms.

    Args:
        site_url: WordPress site URL.
        taxonomy: Custom taxonomy slug (e.g., "clinical_topics").
        days: How many days back to look for posts.

    Returns:
        List of post dicts with keys: id, title, content, link, topics.
    """
    api_base = f"{site_url.rstrip('/')}/wp-json/wp/v2"
    after = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()

    try:
        resp = httpx.get(
            f"{api_base}/posts",
            params={
                "after": after,
                "per_page": 100,
                "orderby": "date",
                "order": "desc",
            },
            timeout=30,
        )
        resp.raise_for_status()
        raw_posts = resp.json()
    except Exception:
        logger.warning("Failed to fetch recent posts from WordPress", exc_info=True)
        return []

    # Fetch taxonomy terms to map IDs to names
    term_map = _fetch_term_map(api_base, taxonomy)

    posts = []
    for p in raw_posts:
        term_ids = p.get(taxonomy, [])
        topics = [term_map[tid] for tid in term_ids if tid in term_map]
        posts.append({
            "id": p["id"],
            "title": p["title"]["rendered"],
            "content": p["content"]["rendered"],
            "link": p["link"],
            "topics": topics,
        })

    logger.info("Fetched %d recent posts from WordPress", len(posts))
    return posts


def _fetch_term_map(api_base: str, taxonomy: str) -> dict[int, str]:
    """Fetch all taxonomy terms and return a mapping of ID to name."""
    try:
        resp = httpx.get(
            f"{api_base}/{taxonomy}",
            params={"per_page": 100},
            timeout=30,
        )
        resp.raise_for_status()
        return {t["id"]: t["name"] for t in resp.json()}
    except Exception:
        logger.warning("Failed to fetch taxonomy terms", exc_info=True)
        return {}


def filter_posts_for_member(
    posts: list[dict],
    member: Member,
) -> list[dict]:
    """Filter posts to only those matching a member's topic preferences.

    If a member has no topic preferences, they receive all posts.
    """
    if not member.topics:
        return posts

    member_topics = set(member.topics)
    return [p for p in posts if member_topics & set(p["topics"])]


def build_member_digest(
    posts: list[dict],
    member: Member,
    date_range: str,
) -> tuple[str, str]:
    """Build markdown and HTML digest for a single member.

    Args:
        posts: Filtered posts for this member.
        member: The member receiving the digest.
        date_range: Human-readable date range.

    Returns:
        Tuple of (html_content, plain_text).
    """
    greeting = member.display_name or "Subscriber"

    md_parts = [
        f"Hello {greeting},\n",
        f"Here are your selected articles for {date_range}:\n",
    ]

    for post in posts:
        topics_str = ", ".join(post["topics"]) if post["topics"] else "General"
        md_parts.append(f"## {post['title']}")
        md_parts.append(f"*{topics_str}*\n")
        md_parts.append(f"[Read full article]({post['link']})\n")
        md_parts.append("---\n")

    md_parts.append(
        "*Article summaries are generated by AI and may contain errors. "
        "Verify findings against primary sources before applying to patient care.*"
    )

    markdown = "\n".join(md_parts)
    html = markdown_to_html(markdown)
    return html, markdown


def send_member_digests(
    posts: list[dict],
    members: list[Member],
    from_address: str,
    subject: str,
    date_range: str,
) -> int:
    """Send filtered digests to all members.

    Args:
        posts: All recent posts from WordPress.
        members: Members with topic preferences.
        from_address: Verified sender email.
        subject: Email subject line.
        date_range: Human-readable date range for digest header.

    Returns:
        Number of emails successfully sent.
    """
    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        logger.warning("RESEND_API_KEY not set, skipping member digests")
        return 0

    resend.api_key = api_key
    sent_count = 0

    for member in members:
        filtered = filter_posts_for_member(posts, member)
        if not filtered:
            logger.info("No matching posts for %s, skipping", member.email)
            continue

        html, plain_text = build_member_digest(filtered, member, date_range)

        try:
            params: resend.Emails.SendParams = {
                "from": from_address,
                "to": [member.email],
                "subject": subject,
                "html": html,
                "text": plain_text,
            }
            resend.Emails.send(params)
            sent_count += 1
        except Exception:
            logger.warning(
                "Failed to send digest to %s", member.email, exc_info=True
            )

    logger.info("Sent %d/%d member digests", sent_count, len(members))
    return sent_count


def run():
    """Main entry point for the member digest script."""
    parser = argparse.ArgumentParser(
        description="Send per-member filtered digests from WordPress"
    )
    parser.add_argument(
        "--domain",
        required=True,
        help="Domain config profile (e.g. stroke, neurology)",
    )
    parser.add_argument(
        "--days",
        type=int,
        default=7,
        help="How many days back to look for new posts (default: 7)",
    )
    args = parser.parse_args()

    wp_config = load_wp_config(domain=args.domain)
    email_config = load_email_config(domain=args.domain)

    if not wp_config.enabled or not wp_config.site_url:
        logger.info("WordPress not configured for domain '%s', exiting", args.domain)
        return

    # Fetch posts and members
    posts = fetch_recent_posts(
        wp_config.site_url,
        wp_config.clinical_topics_taxonomy,
        days=args.days,
    )
    if not posts:
        logger.info("No recent posts found, nothing to send")
        return

    api_secret = os.environ.get(wp_config.env_digest_secret)
    members = fetch_members(wp_config.site_url, api_secret)
    if not members:
        logger.info("No members found, nothing to send")
        return

    # Build date range string
    end = datetime.now()
    start = end - timedelta(days=args.days)
    date_range = f"{start.strftime('%b %d')} – {end.strftime('%b %d, %Y')}"

    subject = email_config.subject.format(
        date_range=date_range, article_count=len(posts)
    )

    send_member_digests(posts, members, email_config.from_address, subject, date_range)


if __name__ == "__main__":
    run()
