#!/usr/bin/env bash
# sync-contracts.sh — Auto-generate contracts.yaml from spec Requires/Provides tables
#
# Requires bash 4+.
#
# Usage:
#   ./scripts/sync-contracts.sh [project-dir]
#
# Parses each docs/specs/*.spec.md for definition references and version pins,
# then outputs a contracts.yaml matching the expected format.
#
# By default writes to contracts.yaml in the project directory.
# Use --dry-run to print to stdout without writing.

set -euo pipefail

if [ -z "${BASH_VERSION:-}" ]; then
  echo "Error: this script requires bash." >&2
  exit 1
fi

DRY_RUN=false
PROJECT_DIR=""

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    *) PROJECT_DIR="$arg" ;;
  esac
done

PROJECT_DIR="${PROJECT_DIR:-$(pwd)}"
SPECS_DIR="$PROJECT_DIR/docs/specs"
CONTRACTS="$PROJECT_DIR/contracts.yaml"

if [ ! -d "$SPECS_DIR" ]; then
  echo "No specs directory found at $SPECS_DIR" >&2
  exit 1
fi

spec_files=("$SPECS_DIR"/*.spec.md)
if [ ! -f "${spec_files[0]}" ]; then
  echo "No spec files found in $SPECS_DIR" >&2
  exit 1
fi

# ── Parse specs ──────────────────────────────────────────────────────

output="# contracts.yaml — version pins for contract test enforcement
# Auto-generated by sync-contracts.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Maps each spec to shared definition versions it depends on.
# Must stay in sync with:
#   1. Each spec's Requires/Provides tables
#   2. Each definition's ## Version header

specs:"

found_any=false

for spec_file in "${spec_files[@]}"; do
  [ ! -f "$spec_file" ] && continue
  spec_name=$(basename "$spec_file" .md)

  # Extract Requires section: find lines with definitions/...@vN
  requires_pins=$(sed -n '/^## Requires/,/^## /p' "$spec_file" \
    | grep -oE 'definitions/[^@|[:space:]]+@v[0-9]+' 2>/dev/null || true)

  # Extract Provides section: find lines with definitions/...@vN
  provides_pins=$(sed -n '/^## Provides/,/^## /p' "$spec_file" \
    | grep -oE 'definitions/[^@|[:space:]]+@v[0-9]+' 2>/dev/null || true)

  # Skip specs with no definition references
  if [ -z "$requires_pins" ] && [ -z "$provides_pins" ]; then
    continue
  fi

  found_any=true
  output+="
  ${spec_name%.spec}:"

  if [ -n "$requires_pins" ]; then
    output+="
    requires:"
    # Deduplicate and sort
    while IFS= read -r pin; do
      [ -z "$pin" ] && continue
      def_path="${pin%%@*}"
      version="${pin##*@}"
      output+="
      $def_path: $version"
    done <<< "$(echo "$requires_pins" | sort -u)"
  fi

  if [ -n "$provides_pins" ]; then
    output+="
    provides:"
    while IFS= read -r pin; do
      [ -z "$pin" ] && continue
      def_path="${pin%%@*}"
      version="${pin##*@}"
      output+="
      $def_path: $version"
    done <<< "$(echo "$provides_pins" | sort -u)"
  fi
done

if [ "$found_any" = false ]; then
  output+=" {}"
fi

output+="
"

if [ "$DRY_RUN" = true ]; then
  echo "$output"
else
  echo "$output" > "$CONTRACTS"
  echo "Updated $CONTRACTS"
fi
